name: Build and Deploy ICS Calendar

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Compile TypeScript
        run: npx tsc

      - name: Generate individual ICS files
        run: |
          node dist/calendar_2021.js
          node dist/calendar_2022.js
          node dist/calendar_2023.js
          node dist/calendar_2024.js
          node dist/calendar_2025.js

      - name: Copy build script
        run: cp build.mjs dist/

      - name: Generate combined ICS files
        run: node dist/build.mjs

      - name: Copy static files
        run: |
          cp index.html dist/
          cp document.md dist/
          cp -r assets dist/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
